import type { ClassDef } from "../types";

export const classDefs: Record<string, ClassDef> = {
  berserker: {
    id: "berserker",
    name: "Berserker",
    keyStats: ["str", "dex"],
    hitDie: "d12",
    startingHp: 20,
    saveProfile: { advantaged: "str", disadvantaged: "int" },
    proficiencies: { weapons: ["all-str"], armor: [] },
    derivations: [],
  },
  cheat: {
    id: "cheat",
    name: "The Cheat",
    keyStats: ["dex", "int"],
    hitDie: "d6",
    startingHp: 10,
    saveProfile: { advantaged: "dex", disadvantaged: "wil" },
    proficiencies: { weapons: ["dex-weapons"], armor: ["leather"] },
    derivations: [],
  },
  commander: {
    id: "commander",
    name: "Commander",
    keyStats: ["str", "int"],
    hitDie: "d10",
    startingHp: 17,
    saveProfile: { advantaged: "str", disadvantaged: "dex" },
    proficiencies: { weapons: ["all-martial"], armor: ["mail", "shields"] },
    derivations: [],
  },
  hunter: {
    id: "hunter",
    name: "Hunter",
    keyStats: ["dex", "wil"],
    hitDie: "d8",
    startingHp: 13,
    saveProfile: { advantaged: "dex", disadvantaged: "int" },
    proficiencies: { weapons: ["dex-weapons"], armor: ["leather"] },
    derivations: [],
  },
  mage: {
    id: "mage",
    name: "Mage",
    keyStats: ["int", "wil"],
    hitDie: "d6",
    startingHp: 10,
    saveProfile: { advantaged: "int", disadvantaged: "str" },
    proficiencies: {
      weapons: ["blades", "staves", "wands"],
      armor: ["cloth"],
    },
    derivations: [
      {
        target: "manaMax",
        label: "Mage Mana",
        value: (ctx) => ctx.int * 3 + ctx.level,
      },
    ],
  },
  oathsworn: {
    id: "oathsworn",
    name: "Oathsworn",
    keyStats: ["str", "wil"],
    hitDie: "d10",
    startingHp: 17,
    saveProfile: { advantaged: "str", disadvantaged: "dex" },
    proficiencies: {
      weapons: ["str-weapons"],
      armor: ["cloth", "leather", "mail", "plate", "shields"],
    },
    derivations: [],
  },
  shadowmancer: {
    id: "shadowmancer",
    name: "Shadowmancer",
    keyStats: ["int", "dex"],
    hitDie: "d8",
    startingHp: 13,
    saveProfile: { advantaged: "int", disadvantaged: "wil" },
    proficiencies: { weapons: ["blades", "wands"], armor: ["cloth"] },
    derivations: [
      {
        target: "manaMax",
        label: "Shadowmancer Mana",
        value: (ctx) => ctx.int * 3 + ctx.level,
      },
    ],
  },
  shepherd: {
    id: "shepherd",
    name: "Shepherd",
    keyStats: ["wil", "str"],
    hitDie: "d10",
    startingHp: 17,
    saveProfile: { advantaged: "wil", disadvantaged: "dex" },
    proficiencies: {
      weapons: ["str-weapons", "wands"],
      armor: ["mail", "shields"],
    },
    derivations: [
      {
        target: "manaMax",
        label: "Shepherd Mana",
        value: (ctx) => ctx.wil * 3 + ctx.level,
      },
    ],
  },
  songweaver: {
    id: "songweaver",
    name: "Songweaver",
    keyStats: ["wil", "int"],
    hitDie: "d8",
    startingHp: 13,
    saveProfile: { advantaged: "wil", disadvantaged: "str" },
    proficiencies: {
      weapons: ["dex-weapons", "wands"],
      armor: ["cloth", "leather"],
    },
    derivations: [
      {
        target: "manaMax",
        label: "Songweaver Mana",
        value: (ctx) => ctx.wil * 3 + ctx.level,
      },
    ],
  },
  stormshifter: {
    id: "stormshifter",
    name: "Stormshifter",
    keyStats: ["wil", "dex"],
    hitDie: "d8",
    startingHp: 13,
    saveProfile: { advantaged: "wil", disadvantaged: "str" },
    proficiencies: {
      weapons: ["staves", "wands"],
      armor: ["cloth", "leather"],
    },
    derivations: [
      {
        target: "manaMax",
        label: "Stormshifter Mana",
        value: (ctx) => ctx.wil * 3 + ctx.level,
      },
    ],
  },
  zephyr: {
    id: "zephyr",
    name: "Zephyr",
    keyStats: ["dex", "str"],
    hitDie: "d8",
    startingHp: 13,
    saveProfile: { advantaged: "dex", disadvantaged: "int" },
    proficiencies: { weapons: ["melee"], armor: [] },
    derivations: [],
  },
};
